import { BookOpen, Download } from "lucide-react";
import { Card, CardHeader, CardTitle, CardContent } from "@/components/ui/card";
import { ScrollArea } from "@/components/ui/scroll-area";
import { Button } from "@/components/ui/button";
import { BeakerContent } from "../ChemistryLab";

interface ObservationNoteProps {
  observations: string[];
  beakerContent: BeakerContent;
}

export const ObservationNote = ({ observations, beakerContent }: ObservationNoteProps) => {
  const exportNotes = () => {
    const notesText = [
      "=== CHEMISTRY LAB NOTEBOOK ===",
      `Date: ${new Date().toLocaleDateString()}`,
      "",
      "EXPERIMENT CONTENTS:",
      `Elements: ${beakerContent.elements.map(e => e.symbol).join(", ") || "None"}`,
      `Compounds: ${beakerContent.compounds.map(c => c.formula).join(", ") || "None"}`,
      `Temperature: ${beakerContent.temperature}°C`,
      `pH: ${beakerContent.ph}`,
      "",
      "REACTIONS OBSERVED:",
      ...beakerContent.reactions.map(r => `- ${r}`),
      "",
      "OBSERVATIONS:",
      ...observations.map(o => `- ${o}`),
      "",
      "Generated by Virtual Chemistry Lab"
    ].join("\n");

    const blob = new Blob([notesText], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `chemistry-lab-notes-${new Date().toISOString().split('T')[0]}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <Card>
      <CardHeader>
        <div className="flex items-center justify-between">
          <CardTitle className="flex items-center gap-2">
            <BookOpen className="h-5 w-5" />
            Lab Notebook
          </CardTitle>
          <Button 
            onClick={exportNotes}
            variant="outline" 
            size="sm"
            disabled={observations.length === 0}
          >
            <Download className="h-4 w-4 mr-2" />
            Export Notes
          </Button>
        </div>
      </CardHeader>
      <CardContent>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          {/* Current Experiment Status */}
          <div className="space-y-4">
            <h3 className="font-semibold text-lg">Current Experiment</h3>
            
            <div className="space-y-3">
              <div>
                <div className="text-sm font-medium text-muted-foreground">Contents:</div>
                <div className="mt-1">
                  {beakerContent.elements.length === 0 && beakerContent.compounds.length === 0 ? (
                    <span className="text-muted-foreground italic">Empty beaker</span>
                  ) : (
                    <div className="flex flex-wrap gap-1">
                      {beakerContent.elements.map(element => (
                        <span key={element.id} className="bg-primary/10 text-primary px-2 py-1 rounded text-xs">
                          {element.symbol}
                        </span>
                      ))}
                      {beakerContent.compounds.map(compound => (
                        <span key={compound.id} className="bg-accent/10 text-accent px-2 py-1 rounded text-xs">
                          {compound.formula}
                        </span>
                      ))}
                    </div>
                  )}
                </div>
              </div>
              
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <div className="text-sm font-medium text-muted-foreground">Temperature</div>
                  <div className="text-lg font-semibold">{beakerContent.temperature}°C</div>
                </div>
                <div>
                  <div className="text-sm font-medium text-muted-foreground">pH Level</div>
                  <div className="text-lg font-semibold">{beakerContent.ph.toFixed(1)}</div>
                </div>
              </div>
              
              {beakerContent.reactions.length > 0 && (
                <div>
                  <div className="text-sm font-medium text-muted-foreground">Active Reactions:</div>
                  <div className="mt-1 space-y-1">
                    {beakerContent.reactions.map((reaction, i) => (
                      <div key={i} className="text-xs bg-success/10 text-success p-2 rounded">
                        {reaction}
                      </div>
                    ))}
                  </div>
                </div>
              )}
            </div>
          </div>

          {/* Observations Log */}
          <div className="space-y-4">
            <h3 className="font-semibold text-lg">Observations Log</h3>
            
            {observations.length === 0 ? (
              <div className="text-muted-foreground italic text-center py-8">
                No observations recorded yet.<br />
                Start experimenting to see observations appear here!
              </div>
            ) : (
              <ScrollArea className="h-64 border rounded-lg p-3">
                <div className="space-y-2">
                  {observations.map((observation, i) => (
                    <div key={i} className="text-sm p-2 bg-muted/50 rounded">
                      {observation}
                    </div>
                  ))}
                </div>
              </ScrollArea>
            )}
          </div>
        </div>

        {/* Scientific Method Guide */}
        <div className="mt-6 p-4 bg-muted/30 rounded-lg">
          <h4 className="font-semibold mb-2">Scientific Method Reminder:</h4>
          <div className="text-sm text-muted-foreground space-y-1">
            <div>1. <strong>Observe:</strong> What do you see happening in the beaker?</div>
            <div>2. <strong>Hypothesize:</strong> What do you think will happen when you add new substances?</div>
            <div>3. <strong>Experiment:</strong> Test your hypothesis by adding elements or compounds</div>
            <div>4. <strong>Record:</strong> Document your observations and results</div>
            <div>5. <strong>Analyze:</strong> Compare your results with your initial hypothesis</div>
          </div>
        </div>
      </CardContent>
    </Card>
  );
};